#!/bin/sh
set -e

# RC: RestCommander

RC_CFG_DIR="/etc/restcommander/"
RC_CFG_FILE=${RC_CFG_DIR}config.toml
RC_PASSWORD_FILE=${RC_CFG_DIR}password-file.sha512
RC_KEY_FILE=${RC_CFG_DIR}key.pem
RC_CERT_FILE=${RC_CFG_DIR}cert.pem
RC_CAPTCHA_FILE=${RC_CFG_DIR}captcha.txt

RC_SRV_DIR="/srv/restcommander/"
RC_WWW_DIR=${RC_SRV_DIR}www/
RC_SAMPLE_WWW_FILE=${RC_WWW_DIR}test.txt
RC_SCRIPTS_DIR=${RC_SRV_DIR}scripts/
RC_TEST_SCRIPT=${RC_SCRIPTS_DIR}test
RC_TEST_SCRIPT_INFO=${RC_SCRIPTS_DIR}test.yml

case "$1" in
  configure)
    if [ ! -f ${RC_CFG_FILE} ]; then
      restcommander sample config > ${RC_CFG_FILE}
      sed -i "s|= \"127.0.0.1\"|= \"0.0.0.0\"|g" ${RC_CFG_FILE}
      sed -i "s|= \"password-file.sha512\"|= \"${RC_CFG_DIR}password-file.sha512\"|g" ${RC_CFG_FILE}
      sed -i "s|= \"cert.pem\"|= \"${RC_CERT_FILE}\"|g" ${RC_CFG_FILE}
      sed -i "s|= \"key.pem\"|= \"${RC_KEY_FILE}\"|g" ${RC_CFG_FILE}
      sed -i "s|= \"scripts\"|= \"${RC_SCRIPTS_DIR}\"|g" ${RC_CFG_FILE}
      sed -i "s|= \"www\"|= \"${RC_WWW_DIR}\"|g" ${RC_CFG_FILE}
      echo "Created new configuration file at " ${RC_CFG_FILE}
    fi
    if [ ! -f ${RC_PASSWORD_FILE} ]; then
      restcommander sha512 admin > ${RC_PASSWORD_FILE}
      echo "Created new password file at " ${RC_PASSWORD_FILE}
    fi
    mkdir -p ${RC_SCRIPTS_DIR}
    if [ ! "$(ls -A ${RC_SCRIPTS_DIR})" ]; then
      restcommander sample script > ${RC_TEST_SCRIPT}
      chmod a+x ${RC_TEST_SCRIPT}
      restcommander sample script-info > ${RC_TEST_SCRIPT_INFO}
      echo "Created new sample script file at " ${RC_TEST_SCRIPT}
    fi
    if [ ! -f ${RC_KEY_FILE} ]; then
      restcommander sample self-signed-key > ${RC_KEY_FILE}
      echo "Created new private-key file at " ${RC_KEY_FILE}
      restcommander sample self-signed-cert > ${RC_CERT_FILE}
      echo "Created new certificate file at " ${RC_CERT_FILE}
    fi
    if [ ! -f ${RC_SAMPLE_WWW_FILE} ]; then
      mkdir -p ${RC_WWW_DIR}
      touch ${RC_SAMPLE_WWW_FILE}
      echo "This is a sample static file to test your configuration." >> ${RC_SAMPLE_WWW_FILE}
      echo "You can access this file at /test.txt ot /static/test.txt to see this text." >> ${RC_SAMPLE_WWW_FILE}
      echo "Created new static test file at " ${RC_SAMPLE_WWW_FILE}
    fi
    if [ ! -f ${RC_CAPTCHA_FILE} ]; then
      rm -rf ${RC_CAPTCHA_FILE}
    fi
    ;;
esac

#DEBHELPER#
